variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  image: registry.gitlab.com/pages/hugo:latest
  stage: build
  script:
    - hugo -b https://zaba505.github.io/ -d ./dist
  artifacts:
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - apk update && apk add openssh-client git
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in DEPLOY_SSH_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git config --global user.email "cakub6@gmx.com"
    - git config --global user.name "zaba505"
    - cat ~/.ssh/known_hosts
    - msg=$(git log -1 --pretty=%B)
    - git clone git@github.com:Zaba505/zaba505.github.io.git public
    - rm -r public/*
    - cd public
    - cp -R ../dist .
    - git add .
    - git commit -m "$msg"
    - git push
