variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  image: registry.gitlab.com/pages/hugo:latest
  stage: build
  script:
    - hugo -b https://zaba505.github.io/ -d ./dist
  artifacts:
    paths:
      - dist

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: deploy
  only:
    - master
  needs: []
  script:
    - hugo -b https://zaba505.gitlab.io/ -d ./dist
  artifacts:
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - apk update && apk add openssh-client git
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git config --global user.email "cakub6@gmx.com"
    - git config --global user.name "zaba505"
    - msg=$(git log -1 --pretty=%B)
    - git clone git@github.com:Zaba505/zaba505.github.io.git public
    - rm -r public/*
    - cp -r dist/. public/
    - cd public
    - git add .
    - git commit -m "$msg"
    - git push
