image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  script:
    - hugo -b https://zaba505.github.io/
  artifacts:
    paths:
      - public

deploy:
  dependencies:
    - build
  script:
    - cd public
    - git add .
    - git commit -m "$(git log -1 --pretty=%B)"
    - git push origin master
