baseURL: 'https://zaba505.dev'
languageCode: 'en-us'
title: 'Zaba505'
theme: 'PaperMod'

menu:
  main:
    - identifier: 'about'
      name: 'About'
      url: '/about'
      weight: 10
    - identifier: 'research'
      name: 'Research'
      url: '/research'
      weight: 20

params:
  author: 'Zaba505'
  description: 'A personal site for showcasing various projects and hosting blog posts'

  profileMode:
    enabled: true
    title: 'Richard Carson Derr'
    subTitle: 'Go priest, Java practitioner, and tinkerer in everything else'

  socialIcons:
    - name: 'github'
      url: 'https://github.com/Zaba505'
    - name: 'gitlab'
      url: 'https://gitlab.com/zaba505'
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/richard-derr-670566138/'